---
driver:
  name: vagrant
  customize:
   memory: 4096
  - synced_folders: [["/vagrant/binaries", "/vagrant/binaries"]]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
    attributes:
